services:
  - type: web
    name: fin-guru-backend
    env: python
    plan: free
    rootDir: fin_rag_backend
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn server:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: GEMINI_API_KEY
        sync: false
